# Generated by Django 3.2.5 on 2021-11-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=30, unique=True, verbose_name='patient_name')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patient',
                'ordering': ['-patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('event_value', models.PositiveIntegerField(blank=True, default=0, verbose_name='even value')),
                ('event_unit', models.CharField(blank=True, max_length=100, verbose_name='event unit')),
                ('event_time', models.DateTimeField(verbose_name='event time')),
                ('event_type', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.event_type', to_field='type_name', verbose_name='event type')),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
                'ordering': ['-event_id'],
            },
        ),
    ]
